dist: bionic
language: java
sudo: false
install: true
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
env:
  #- MVN_ARGS="quarkus/pom.xml install && mvn -f quarkus/pom.xml -Pnative -Dnative-image.docker-build=true && docker-compose -f quarkus/src/main/docker/docker-compose.yml build app"
  - SCRIPT="mvn -f quarkus/pom.xml install"
  - SCRIPT="mvn -f quarkus/pom.xml -Pnative -Dnative-image.docker-build=true"
  - SCRIPT="mvn -f springboot/pom.xml install"
  - SCRIPT="mvn -f wildfly/pom.xml install -Pwildfly"
  - SCRIPT="mvn -f wildfly/pom.xml install -Pdocker"
script: $SCRIPT
