dist: bionic
os: linux
language: java
install: true
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
env:
  - SCRIPT="mvn -f quarkus/pom.xml package"
  - SCRIPT="mvn -pl :openfeign,:springboot install"
  - SCRIPT="mvn -f wildfly/pom.xml package -Pwildfly"
  - SCRIPT="mvn -f wildfly/pom.xml package -Pdocker"
script: $SCRIPT
