dist: bionic
language: java
sudo: false
jdk:
  - openjdk11
script:
- mvn -f springboot/pom.xml clean install
- mvn -f wildfly/pom.xml clean install -Pdocker
- mvn -f quarkus/pom.xml package quarkus:build && mvn -Pnative -Dnative-image.docker-build=true && docker-compose -f src/main/docker/docker-compose.yml build app
