dist: bionic
language: java
sudo: false
install: true
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
script:
- mvn -f springboot/pom.xml clean install
- mvn -f wildfly/pom.xml clean install -Pwildfly
- mvn -f wildfly/pom.xml clean install -Pdocker
- mvn -f quarkus/pom.xml package -Dquarkus.profile=dev
  && mvn -f quarkus/pom.xml -Pnative -Dnative-image.docker-build=true
  && docker-compose -f quarkus/src/main/docker/docker-compose.yml build app
