hibernate:
  cache:
    use_second_level_cache: true
    region:
      factory_class: org.hibernate.cache.ehcache.internal.EhcacheRegionFactory
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /micro
spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false
  data:
    rest:
      base-path: /api
  http:
    log-request-details: true
  output:
    ansi:
      enabled: always
security:
  jwt:
    expiration: 3600
    secret: VerySecretJwtKey
    encodeRolesInJwt: true
---
spring:
  profiles: production
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics
